#cloud-config
autoinstall:
  version: 1
  codecs:
    install: true
  drivers:
    install: true
  packages:
    - flatpak
    - git
  snaps:
    - name: libreoffice
    - name: code
      classic: true
    - name: chromium
  identity:
    hostname: super-codeurs
    username: codeur-admin
    password: "$6$NC9BGiuKLATCuVSF$kY5lHr/0yLjXqkJdxZfaTWTbBGI3neQqdRPEjIrGePg9xXDZqIt8nKhtvemmy1U44nQcz/H/cdDym6HKRW6KX/"
  user-data:
    users:
      - name: codeur-sup
        gecos: codeur-sup
        groups: [users]
        shell: /bin/bash
        lock_passwd: false
        passwd: "$6$ggqZrlQCFf.58g6e$o01kyIbBCUIf9QND.fKsJp7nUpt0k/FS/YuIndqy3yQlzW0IMFFTKiVdaOuSMFXkXpx0C2aZPoyU.uxRB/7II."
  keyboard:
    layout: fr
    variant: azerty
  locale: fr_FR.UTF-8
  timezone: Europe/Paris
  late-commands:
    - curtin in-target -- flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    - curtin in-target -- flatpak install -y flathub org.mobsya.ThymioSuite
    # Cf https://www.thymio.org/fr/installation-sous-linux/
    - curtin in-target -- printf 'SUBSYSTEM=="usb", ATTRS{idVendor}=="0617", ATTRS{idProduct}=="000a", MODE="0666"\nSUBSYSTEM=="usb", ATTRS{idVendor}=="0617", ATTRS{idProduct}=="000c", MODE="0666"\n' | tee /etc/udev/rules.d/99-mobsya.rules && udevadm control --reload-rules
    - curtin in-target -- flatpak install -y flathub edu.mit.Scratch
